lessons
randori
	^ Lesson title: 'Randori' lesson: '
	"This Jam session is a regular Randori, but with some differences.
	Randori consists of working in pairs when applying TDD to solve a problem.
	When it is your turn, you will be given a failing test. Your first task is to make it pass. You might need the help of the JamSessionHost.
	Your second task is to write an additional test and ask another attendee to take care of it."
	ProfStef next.'